spring:
 cloud:
   gateway:
     routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
          - Path=/restaurant/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
          - Path=/user/**
        - id: food-catalogue-service
          uri: lb://FOOD-CATALOGUE-SERVICE
          predicates:
          - Path=/foodCatalogue/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path=/order/**
 application:
    name: API-GATEWAY

server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/