server:
  port: 9093

eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
mangement:
     tracing:
         sampling:
            probability: 1.0